### ISSUE TITLE
Вечное окно загрузки

### ISSUE THREAD

**Issue by caimanchik** [Fidden/YandexMusicElectron#4]
Когда забилдил под макось, после ввода токена вечный экран загрузки( И какой токен вводить надо? Пасиба за ответ

**Comment by Fidden** [comment]
Самый простой способ получения токена: https://github.com/MarshalX/yandex-music-api/discussions/513#discussioncomment-2729781

**Comment by caimanchik** [comment]
А ля. Не заметил в ридми. В глаза долблюсь получаеца)
